name: test_util
description: 'Helpers and utilities for testing: running Dart processes and expecting output.'
repository: https://github.com/alexeyinkin/dart-test-util.git
version: 0.1.1

environment:
  sdk: ^3.0.0

topics:
  - testing
  - cli

dependencies:
  collection: ^1.18.0
  test: ^1.25.5

dev_dependencies:
  total_lints: ^3.4.0
